import { useEffect, useState } from 'react'
import { ArrowRight, CloudOff, LockKeyhole, Menu, Radio, ShieldCheck, Smartphone, WifiOff, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { publicHealthService, type PublicHealthResult } from '@/services/public-health.service'

const controls = [
  ['Daily use limits', 'A DPC policy can define daily active-use limits and the restricted mode applied after the allowance.', 'Screen Time'],
  ['Focused web access', 'Blocked-domain evidence is privacy-limited: raw URLs and permitted browsing are never retained.', 'Web filtering'],
  ['Approved learning apps', 'Named policy modes give schools a controlled application surface for the learning day.', 'App access'],
  ['Persistent Block', 'Authorized operators can set a Block override that remains in force until explicitly cleared.', 'Device control'],
]

function Badge({ value, label }: { value: PublicHealthResult | null; label: string }) { const ready = value?.status === 'ready' || value?.status === 'running'; return <span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/8 px-3 py-2 text-xs font-semibold text-white/80"><span className={`size-2 rounded-full ${ready ? 'bg-lime-300' : 'bg-amber-300'}`} />{label}: {ready ? 'available' : value?.status === 'unavailable' ? 'unavailable' : 'checking'}</span> }

export function LandingPage() {
  const [health, setHealth] = useState<PublicHealthResult | null>(null)
  const [ready, setReady] = useState<PublicHealthResult | null>(null)
  const [open, setOpen] = useState(false)
  useEffect(() => { void Promise.all([publicHealthService.checkHealth(), publicHealthService.checkReadiness()]).then(([h, r]) => { setHealth(h); setReady(r) }) }, [])
  return <main className="min-h-screen bg-[#f6f5f1] text-[#10211d]"><a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:bg-white focus:p-3">Skip to content</a>
    <section className="relative overflow-hidden bg-[#10211d] text-white"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(#fff_1px,transparent_1px),linear-gradient(90deg,#fff_1px,transparent_1px)] [background-size:64px_64px]" /><div className="relative mx-auto max-w-7xl px-5 sm:px-8"><nav className="flex h-20 items-center justify-between border-b border-white/10"><Link to="/" className="flex items-center gap-3 text-lg font-semibold"><span className="grid size-9 place-items-center rounded-xl bg-lime-300 text-[#10211d]"><ShieldCheck className="size-5" /></span>EduGD</Link><div className={`${open ? 'absolute left-5 right-5 top-20 flex' : 'hidden'} z-20 flex-col gap-4 rounded-2xl bg-[#183a30] p-5 md:static md:flex md:flex-row md:items-center md:bg-transparent md:p-0`}><a href="#controls" onClick={() => setOpen(false)} className="text-sm text-white/70">Controls</a><a href="#model" onClick={() => setOpen(false)} className="text-sm text-white/70">Operating model</a><Link to="/login" className="rounded-full bg-lime-300 px-5 py-2.5 text-sm font-bold text-[#10211d]">Admin console</Link></div><button type="button" className="md:hidden" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></nav>
      <div className="grid gap-12 py-18 lg:grid-cols-[1fr_.9fr] lg:items-center lg:py-28"><div><div className="flex flex-wrap gap-2"><Badge value={health} label="API" /><Badge value={ready} label="Readiness" /></div><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-lime-300">School-owned Android learning</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.95] tracking-[-.05em] sm:text-7xl">Device control that keeps the school day in focus.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">EduGD gives schools an accountable control surface for Android learning devices, designed for local enforcement when connectivity cannot be assumed.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/login" className="inline-flex items-center gap-2 rounded-full bg-lime-300 px-6 py-3.5 font-bold text-[#10211d]">Access admin console <ArrowRight className="size-4" /></Link><a href="#model" className="rounded-full border border-white/25 px-6 py-3.5 font-bold">See how it works</a></div><p className="mt-6 text-xs text-white/45">Public status checks expose service availability only. Device, policy, and school data remain protected.</p></div>
        <DeviceArtwork /></div></div></section>
    <div id="main"><section id="controls" className="mx-auto max-w-7xl px-5 py-22 sm:px-8"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">DPC control surface</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Four controls. One clear operational model.</h2><p className="mt-5 max-w-md leading-7 text-slate-600">The dashboard reflects real policy, override, and evidence records from the EduGD API. It does not simulate fleet data.</p></div><div className="grid gap-4 sm:grid-cols-2">{controls.map(([title, detail, badge], index) => <article key={title} className={`rounded-2xl border border-slate-200 bg-white p-6 shadow-sm ${index === 0 ? 'sm:col-span-2 sm:grid sm:grid-cols-[1fr_auto] sm:gap-8' : ''}`}><div><span className="rounded-full border border-emerald-700/20 bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">{badge}</span><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{detail}</p></div>{index === 0 && <ClockDial />}</article>)}</div></div></section>
      <section id="model" className="bg-[#e2ecd7] px-5 py-22 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-800">Built around real school conditions</p><div className="mt-5 grid gap-8 lg:grid-cols-3"><h2 className="text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Local decisions. Accountable reconnection.</h2><article className="border-t border-[#10211d]/20 pt-5"><CloudOff className="size-6 text-emerald-800" /><h3 className="mt-5 font-semibold">Offline continuity</h3><p className="mt-2 leading-7 text-slate-700">Policies are designed for local DPC enforcement, so an interrupted connection does not become an interrupted school day.</p></article><article className="border-t border-[#10211d]/20 pt-5"><Radio className="size-6 text-emerald-800" /><h3 className="mt-5 font-semibold">Evidence with limits</h3><p className="mt-2 leading-7 text-slate-700">Operators review administrative and blocked-domain evidence without collecting full URLs or permitted browsing history.</p></article></div><div className="mt-12 grid gap-3 sm:grid-cols-4">{[['School leaders', ShieldCheck], ['ICT administrators', Smartphone], ['Teachers', WifiOff], ['Parents & guardians', LockKeyhole]].map(([label, Icon]) => { const Component = Icon as typeof ShieldCheck; return <div key={label as string} className="rounded-xl border border-[#10211d]/15 bg-white/70 p-4"><Component className="size-5 text-emerald-800" /><p className="mt-5 text-sm font-semibold">{label as string}</p></div> })}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-22 sm:px-8"><div className="rounded-[2rem] bg-[#10211d] p-8 text-white sm:p-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-lime-300">Governed administration</p><div className="mt-5 flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><h2 className="max-w-2xl text-4xl font-semibold tracking-[-.04em]">Give digital learning a system the school can explain and govern.</h2><p className="mt-4 max-w-xl text-white/65">EduGD is built for school-owned Android phones and tablets. Android DPC enforcement remains subject to device certification and rollout.</p></div><Link to="/login" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-lime-300 px-6 py-3.5 font-bold text-[#10211d]">Open admin console <ArrowRight className="size-4" /></Link></div></div></section></div>
    <footer className="border-t border-slate-200 px-5 py-8 text-sm text-slate-500 sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-3"><span>EduGD · School-owned Android learning</span><span>Product narrative informed by supplied local reference materials.</span></div></footer>
  </main>
}

function DeviceArtwork() { return <div aria-label="Neutral Android phone and tablet illustration" className="relative mx-auto h-105 w-full max-w-xl"><div className="absolute right-3 top-0 h-91 w-45 rotate-6 rounded-[2.4rem] border-8 border-[#253f36] bg-[#f7f8f2] p-3 shadow-2xl"><div className="rounded-[1.7rem] bg-[#e4efc8] p-4 text-[#10211d]"><span className="text-[10px] font-bold uppercase tracking-widest">EduGD</span><p className="mt-12 text-lg font-semibold leading-tight">School day controls</p><div className="mt-7 h-2 rounded-full bg-[#10211d]/15" /><div className="mt-3 h-2 w-2/3 rounded-full bg-[#10211d]/15" /></div></div><div className="absolute bottom-0 left-0 h-75 w-78 -rotate-6 rounded-[2rem] border-9 border-[#253f36] bg-[#f7f8f2] p-4 shadow-2xl"><div className="h-full rounded-[1.25rem] bg-[#dfe9d2] p-5 text-[#10211d]"><div className="flex justify-between text-xs font-bold"><span>CONTROL ROOM</span><span className="rounded-full bg-[#10211d] px-2 py-1 text-white">ANDROID</span></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white p-3"><p className="text-[10px] text-slate-500">Policy</p><p className="mt-2 font-semibold">Verified</p></div><div className="rounded-xl bg-white p-3"><p className="text-[10px] text-slate-500">Evidence</p><p className="mt-2 font-semibold">Private</p></div></div><div className="mt-4 rounded-xl bg-[#10211d] p-4 text-sm font-semibold text-white">Local policy evaluation</div></div></div></div> }
function ClockDial() { return <div className="hidden self-center rounded-full border-8 border-emerald-100 p-6 text-center sm:block"><span className="text-2xl font-semibold">24h</span><p className="text-[10px] uppercase tracking-widest text-slate-500">Daily window</p></div> }
