import { useState } from 'react'
import { Check, ChevronDown, Database, ShieldCheck, Sparkles } from 'lucide-react'
import { CTA, Eyebrow, SectionHeading } from '@/components/marketing/MarketingPrimitives'
import { BRAND_NAME } from '@/content/brand'

const features = [['Policy lifecycle', 'Create, assign and reconcile school-day controls with a clear audit trail.'], ['Offline enforcement', 'Keep the approved operating model effective when connectivity disappears.'], ['Evidence by design', 'Review privacy-aware status, acknowledgements and security events.']] as const
const faqs = [['Is EduGD a commercial MDM platform?', 'No. EduGD is an academic proof-of-concept with a deliberately documented scope and release gates.'], ['What does offline-first mean here?', 'The device-side contract is designed to preserve approved policy behavior while a device is offline, then reconcile signed state when it reconnects.'], ['Are Android DPC and production rollout included?', 'They remain separate verification gates. This public site describes repository-backed contracts without claiming physical certification.']] as const

export function LandingPage() {
  const [selected, setSelected] = useState(0); const [openFaq, setOpenFaq] = useState<number | null>(null)
  return <div className="overflow-hidden">
    <section id="hero" className="bg-[#10211d] text-white"><div className="mx-auto flex max-w-7xl flex-col items-center px-5 pb-16 pt-28 text-center sm:px-8 sm:pt-36"><Eyebrow>Offline-first school device governance</Eyebrow><h1 className="mt-5 max-w-4xl text-5xl font-bold leading-[.98] tracking-[-.055em] sm:text-7xl">Keep the school day <span className="text-lime-300">in focus</span>, even when the network cannot.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">{BRAND_NAME} gives Ugandan secondary schools an accountable control surface for phone-use policies on school-owned Android devices.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><CTA href="/product">Explore the product</CTA><CTA href="/login" secondary>Open admin console</CTA></div><p className="mt-6 text-xs text-white/50">Repository-backed public explanation. Android DPC certification and production rollout remain separate gates.</p><div className="mt-14 w-full max-w-5xl rounded-[2rem] border border-white/20 bg-white/10 p-2 shadow-2xl"><div className="grid min-h-72 place-items-center rounded-[1.6rem] bg-[#e5f0dc] p-8 text-left text-slate-950 sm:min-h-105"><div className="grid w-full max-w-3xl gap-4 sm:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl bg-emerald-950 p-5 text-white"><ShieldCheck className="size-8 text-lime-300" /><p className="mt-12 text-sm text-white/60">Policy control surface</p><p className="mt-2 text-2xl font-bold">School day, made accountable.</p></div><div className="grid gap-4 sm:grid-cols-2"><Preview label="Devices" value="Connected evidence" /><Preview label="Policy" value="Signed revision" /><Preview label="Network" value="Offline-ready" /><Preview label="Audit" value="Privacy-safe" /></div></div></div></div></div></section>
    <section id="logoCollection" className="mx-auto max-w-7xl px-5 py-12 text-center sm:px-8"><p className="text-sm font-semibold text-slate-500">Built around clear boundaries, verified evidence and school context</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm font-bold text-emerald-900 sm:grid-cols-4">{['Policy', 'Devices', 'Evidence', 'Security'].map(item => <span key={item} className="rounded-xl bg-emerald-50 px-4 py-4">{item}</span>)}</div></section>
    <section id="features" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><SectionHeading eyebrow="Capabilities" title="A connected operating model for accountable device use.">EduGD connects administrator intent with device status, signed policy state and security-relevant evidence.</SectionHeading><div className="mt-10 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="flex gap-2 overflow-auto lg:block">{features.map(([title], index) => <button key={title} type="button" onClick={() => setSelected(index)} className={`whitespace-nowrap rounded-full px-4 py-3 text-left text-sm font-bold lg:mb-3 lg:block lg:w-full lg:rounded-2xl ${selected === index ? 'bg-emerald-900 text-white' : 'bg-emerald-50 text-emerald-950'}`}>{title}</button>)}</div><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10"><Sparkles className="size-8 text-emerald-700" /><h3 className="mt-10 text-3xl font-bold">{features[selected][0]}</h3><p className="mt-4 max-w-xl text-lg leading-8 text-slate-600">{features[selected][1]}</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{['Defined contract', 'Auditable state', 'Fail-closed scope'].map(item => <div key={item} className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{item}</div>)}</div></article></div></section>
    <section id="highlights" className="bg-[#e5f0dc] px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="How it works" title="From policy decision to accountable check-in." /><div className="mt-10 grid gap-4 md:grid-cols-4">{[['01', 'Create', 'Author the school-day operating model.'], ['02', 'Assign', 'Bind an approved revision to a device.'], ['03', 'Enforce', 'Keep controls meaningful offline.'], ['04', 'Reconcile', 'Review signed state and evidence.']].map(([number, title, body]) => <article key={number} className="border-t border-emerald-900/20 pt-5"><span className="font-bold text-emerald-800">{number}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-700">{body}</p></article>)}</div></div></section>
    <section id="testimonials" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><SectionHeading eyebrow="Evidence boundaries" title="A public story grounded in what the repository can prove." /><div className="mt-10 grid gap-5 md:grid-cols-3">{['No unnecessary device data', 'Signed policy and audit contracts', 'Android verification clearly separated'].map(title => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Database className="size-6 text-emerald-700" /><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">EduGD keeps the claim aligned with the current proof-of-concept boundary.</p></article>)}</div></section>
    <section id="pricing" className="bg-slate-950 px-5 py-16 text-white sm:px-8 sm:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Readiness tiers" title="A clear path from contract to certified operation.">Each tier describes evidence and readiness, not a commercial subscription.</SectionHeading><div className="mt-10 grid gap-5 md:grid-cols-3">{[['Repository', 'Contracts and admin surface'], ['Staging', 'Verified integration boundary'], ['Production', 'Physical release decision']].map(([title, subtitle]) => <article key={title} className="rounded-3xl border border-white/15 bg-white/5 p-6"><h3 className="text-2xl font-bold">{title}</h3><p className="mt-2 text-white/60">{subtitle}</p><ul className="mt-8 space-y-3 text-sm text-white/80">{['Signed contract', 'Auditable evidence', 'Explicit release gate'].map(point => <li key={point} className="flex gap-2"><Check className="size-4 text-lime-300" />{point}</li>)}</ul></article>)}</div></div></section>
    <section id="faq" className="mx-auto max-w-4xl px-5 py-16 sm:px-8 sm:py-24"><h2 className="text-3xl font-bold sm:text-5xl">Frequently asked questions</h2><div className="mt-8 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white">{faqs.map(([question, answer], index) => <div key={question}><button type="button" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left font-semibold"><span>{question}</span><ChevronDown className={`size-5 transition-transform ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <p className="px-5 pb-5 leading-7 text-slate-600">{answer}</p>}</div>)}</div></section>
  </div>
}
function Preview({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-emerald-900/10 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-3 font-bold text-emerald-900">{value}</p></div> }
