import { CheckCircle2, Database } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { capabilities } from '@/content/marketing'
import { BRAND_NAME } from '@/content/brand'
import { CTA, Eyebrow, FeatureCard } from '@/components/marketing/MarketingPrimitives'

const details: Record<string, [string, string, string[]]> = { 'offline-enforcement': ['Offline-first enforcement', 'Design policy enforcement for school conditions where connectivity cannot be assumed.', ['Local device-side policy evaluation is part of the intended operating model.', 'Reconnection provides a path for status and policy state synchronization.', 'Android DPC rollout and certification remain external verification requirements.']], 'policy-management': ['Policy management', 'Give authorised administrators a clear path from policy creation to assignment and review.', ['Create and inspect phone-use policies.', 'Assign policies to managed devices.', 'Track acknowledgements and policy state through the administrator surface.']], 'device-management': ['Device management', 'Maintain an accountable view of school-owned Android devices and their operational status.', ['Review device enrollment and status information.', 'Use check-ins to understand device connectivity.', 'Keep private device records behind the authenticated application.']], 'audit-and-forensics': ['Audit and forensics', 'Make security-relevant events reviewable while keeping evidence boundaries explicit.', ['Review security-event audit records.', 'Support selected forensic verification where implemented.', 'Avoid treating a PoC audit trail as a complete forensic platform.']], security: ['Security by design', 'Build the public story around authorization, privacy, and accountable evidence.', ['Protected administrator routes and server-side authorization.', 'Secure identity and synchronization principles where implemented.', 'Privacy-limited evidence and fail-closed security controls.']] }
export function ProductPage() { return <Page title="A focused operating model for school-owned Android devices" eyebrow="Product overview" intro={`${BRAND_NAME} connects policy decisions, device status, and accountable evidence without pretending to be a full commercial MDM platform.`}><div className="grid gap-4 md:grid-cols-3">{[['Administrators', 'Create and assign policies from the protected console.'], ['Devices', 'Apply the operating model to school-owned Android hardware.'], ['Evidence', 'Review status, acknowledgements, and security events.']].map(([title, text]) => <FeatureCard key={title} title={title} text={text} />)}</div></Page> }
export function FeaturesPage() { return <Page title="Capabilities grounded in the current PoC" eyebrow="Capabilities" intro={`Explore the small set of capabilities ${BRAND_NAME} can explain clearly today.`}><div className="grid gap-4 md:grid-cols-2">{capabilities.map(item => <FeatureCard key={item.slug} title={item.title} text={`${item.summary} ${item.status}.`} href={`/features/${item.slug}`} />)}</div></Page> }
export function FeatureDetailPage() { const { slug = '' } = useParams(); const [title, intro, bullets] = details[slug] ?? details.security; return <Page title={title} eyebrow="Capability detail" intro={intro}><div className="grid gap-8 lg:grid-cols-[1fr_.7fr]"><div className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-bold">What this means in {BRAND_NAME}</h2><ul className="mt-6 space-y-4">{bullets.map(bullet => <li key={bullet} className="flex gap-3 leading-7 text-slate-700"><CheckCircle2 className="mt-1 size-5 shrink-0 text-emerald-700" />{bullet}</li>)}</ul></div><ScopeNote /></div></Page> }
export function HowItWorksPage() { return <Page title="From policy decision to accountable check-in" eyebrow="How it works" intro={`${BRAND_NAME} describes a four-stage lifecycle between the administrator, the API, and the managed Android device.`}><div className="grid gap-4 md:grid-cols-4">{['Create a policy', 'Assign to devices', 'Enforce locally', 'Synchronize on return'].map((title, index) => <article key={title} className="rounded-2xl bg-emerald-950 p-6 text-white"><span className="text-lime-300">0{index + 1}</span><h2 className="mt-10 text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-white/70">The public model separates administrative intent from device-side operation and reconnection.</p></article>)}</div><ScopeNote /></Page> }
export function SchoolsPage() { return <Page title="Designed around the school day" eyebrow="For schools" intro={`${BRAND_NAME} gives different school stakeholders a shared vocabulary for device governance.`}><div className="grid gap-4 md:grid-cols-2">{[['ICT administrators', 'Enroll devices, assign policies, review check-ins.'], ['School leadership', 'Understand policy status and operational accountability.'], ['Teachers', 'Work within a defined learning-device policy.'], ['Security reviewers', 'Examine security-event records and evidence boundaries.']].map(([title, text]) => <FeatureCard key={title} title={title} text={text} />)}</div></Page> }
export function SecurityPage() { return <Page title="Security that stays within the evidence" eyebrow="Security" intro={`${BRAND_NAME}’s public security story is about boundaries: protected access, accountable records, and no unnecessary collection.`}><div className="grid gap-4 md:grid-cols-3">{[['Protected access', 'Authentication and authorization keep administrative data behind the application.'], ['Privacy-aware evidence', 'Public pages do not expose device, school, policy, or audit records.'], ['Fail-closed principles', 'Security controls are designed to avoid silently granting access when conditions fail.']].map(([title, text]) => <FeatureCard key={title} title={title} text={text} />)}</div></Page> }
export function ArchitecturePage() { return <Page title="A simple architecture with an explicit boundary" eyebrow="Architecture" intro="The repository documents the web administrator surface and backend contracts; the Android DPC remains an external verification boundary."><div className="rounded-3xl bg-slate-950 p-8 text-white"><div className="grid gap-4 md:grid-cols-5">{['Administrator', 'React + Vite', 'Flask API', 'PostgreSQL / Redis', 'Android DPC'].map((item, index) => <div key={item} className="rounded-2xl border border-white/15 bg-white/5 p-5"><span className="text-sm text-lime-300">0{index + 1}</span><p className="mt-8 font-bold">{item}</p></div>)}</div><p className="mt-8 max-w-2xl text-white/70">Repository-verified components and external verification requirements are intentionally shown separately.</p></div></Page> }
export function ResourcesPage() { return <Page title="Resources for understanding the PoC" eyebrow="Resources" intro={`Start with the ${BRAND_NAME} operating model, then inspect the architecture and security boundaries.`}><div className="grid gap-4 md:grid-cols-3">{[['How it works', '/how-it-works', 'Follow the policy lifecycle.'], ['Architecture', '/architecture', 'See the system boundary.'], ['Security', '/security', 'Review the trust model.'], ['About the PoC', '/about', 'Understand the scope.'], ['For schools', '/schools', 'Explore stakeholder context.'], ['Contact', '/contact', 'Ask for a walkthrough.']].map(([title, href, text]) => <FeatureCard key={href} title={title} text={text} href={href} />)}</div></Page> }
export function AboutPage() { return <Page title="An academic project with transparent scope" eyebrow="About the PoC" intro={`${BRAND_NAME} is a final-year academic Proof-of-Concept for offline-first phone-use policy enforcement on school-owned Android devices in Ugandan secondary schools.`}><div className="max-w-3xl space-y-5 leading-8 text-slate-700"><p>The project explores how policy management, device status, offline operation, and security-event evidence can fit together in a local school context.</p><p>It is not presented as a finished commercial MDM/UEM platform. Android DPC validation, production rollout, and hosted-environment readiness remain separate engineering and operational gates.</p></div></Page> }
export function ContactPage() { return <Page title={`Start a conversation about ${BRAND_NAME}`} eyebrow="Contact" intro="For a walkthrough or academic discussion, contact the project team without sending student, device, credential, or sensitive school data through this public page."><div className="rounded-2xl border border-slate-200 bg-white p-7"><p className="leading-7 text-slate-600">A real submission endpoint is not part of the current frontend contract. Connect an approved mail or form service before adding collection behavior.</p><a className="mt-6 inline-flex rounded-full border border-slate-300 px-5 py-3 font-bold text-slate-800" href="/about">Read the PoC scope</a></div></Page> }
function Page({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) { return <div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="mb-12 max-w-3xl"><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">{title}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{intro}</p></div>{children}<div className="mt-14"><CTA href="/login">Open admin console</CTA></div></div> }
function ScopeNote() { return <aside className="rounded-2xl bg-[#e5f0dc] p-7"><Database className="size-6 text-emerald-800" /><h2 className="mt-5 text-xl font-bold">Scope note</h2><p className="mt-3 leading-7 text-slate-700">This public explanation uses repository evidence and marks Android DPC behavior, device certification, and production operation as separate verification requirements.</p></aside> }
