import { CheckCircle2, Database } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { capabilities } from '@/content/marketing'
import { BRAND_NAME } from '@/content/brand'
import { useLandingLanguage } from '@/i18n/useLandingLanguage'
import { CTA, Eyebrow, FeatureCard } from '@/components/marketing/MarketingPrimitives'

const featureSlugs = ['offline-enforcement', 'policy-management', 'device-management', 'audit-and-forensics', 'security'] as const

function Page({ prefix, eyebrow, title, intro, children }: { prefix: string; eyebrow: string; title: string; intro: string; children: React.ReactNode }) {
  const { text } = useLandingLanguage()
  return <div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="mb-12 max-w-3xl"><Eyebrow>{text(`${prefix}.eyebrow`, eyebrow)}</Eyebrow><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">{text(`${prefix}.title`, title)}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{text(`${prefix}.intro`, intro)}</p></div>{children}<div className="mt-14"><CTA href="/login">{text('common.open_admin', 'Open admin console')}</CTA></div></div>
}

function TranslatedCard({ prefix, title, body, href }: { prefix: string; title: string; body: string; href?: string }) {
  const { text } = useLandingLanguage()
  return <FeatureCard title={text(`${prefix}.title`, title)} text={text(`${prefix}.text`, body)} href={href} />
}

export function ProductPage() { return <Page prefix="product" eyebrow="Product overview" title="A focused operating model for school-owned Android devices" intro={`${BRAND_NAME} connects policy decisions, device status, and accountable evidence without pretending to be a full commercial MDM platform.`}><div className="grid gap-4 md:grid-cols-3"><TranslatedCard prefix="product.administrators" title="Administrators" body="Create and assign policies from the protected console." /><TranslatedCard prefix="product.devices" title="Devices" body="Apply the operating model to school-owned Android hardware." /><TranslatedCard prefix="product.evidence" title="Evidence" body="Review status, acknowledgements, and security events." /></div></Page> }

export function FeaturesPage() { const { text } = useLandingLanguage(); return <Page prefix="features" eyebrow="Capabilities" title="Capabilities grounded in the current PoC" intro={`Explore the small set of capabilities ${BRAND_NAME} can explain clearly today.`}><div className="grid gap-4 md:grid-cols-2">{capabilities.map(item => <FeatureCard key={item.slug} title={text(`feature.${item.slug}.title`, item.title)} text={`${text(`feature.${item.slug}.intro`, item.summary)} ${text(`feature.${item.slug}.status`, item.status)}.`} href={`/features/${item.slug}`} />)}</div></Page> }

export function FeatureDetailPage() { const { text } = useLandingLanguage(); const { slug = '' } = useParams(); const selected = featureSlugs.includes(slug as typeof featureSlugs[number]) ? slug : 'security'; const bullets = [1, 2, 3].map(index => text(`feature.${selected}.bullet${index}`, '')); return <Page prefix="feature.detail" eyebrow="Capability detail" title={text(`feature.${selected}.title`, 'Security by design')} intro={text(`feature.${selected}.intro`, 'Build the public story around authorization, privacy, and accountable evidence.')}><div className="grid gap-8 lg:grid-cols-[1fr_.7fr]"><div className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-bold">{text('feature.detail.what_this_means', `What this means in ${BRAND_NAME}`)}</h2><ul className="mt-6 space-y-4">{bullets.map((bullet, index) => <li key={index} className="flex gap-3 leading-7 text-slate-700"><CheckCircle2 className="mt-1 size-5 shrink-0 text-emerald-700" />{bullet}</li>)}</ul></div><ScopeNote /></div></Page> }

export function HowItWorksPage() { const { text } = useLandingLanguage(); return <Page prefix="how-page" eyebrow="How it works" title="From policy decision to accountable check-in" intro={`${BRAND_NAME} describes a four-stage lifecycle between the administrator, the API, and the managed Android device.`}><div className="grid gap-4 md:grid-cols-4">{[1, 2, 3, 4].map(index => <article key={index} className="rounded-2xl bg-emerald-950 p-6 text-white"><span className="text-lime-300">0{index}</span><h2 className="mt-10 text-xl font-bold">{text(`how-page.card${index}`, '')}</h2><p className="mt-3 text-sm leading-6 text-white/70">{text('how-page.card_body', 'The public model separates administrative intent from device-side operation and reconnection.')}</p></article>)}</div><ScopeNote /></Page> }

export function SchoolsPage() { return <Page prefix="schools" eyebrow="For schools" title="Designed around the school day" intro={`${BRAND_NAME} gives different school stakeholders a shared vocabulary for device governance.`}><div className="grid gap-4 md:grid-cols-2"><TranslatedCard prefix="schools.ict" title="ICT administrators" body="Enroll devices, assign policies, review check-ins." /><TranslatedCard prefix="schools.leadership" title="School leadership" body="Understand policy status and operational accountability." /><TranslatedCard prefix="schools.teachers" title="Teachers" body="Work within a defined learning-device policy." /><TranslatedCard prefix="schools.reviewers" title="Security reviewers" body="Examine security-event records and evidence boundaries." /></div></Page> }

export function SecurityPage() { return <Page prefix="security" eyebrow="Security" title="Security that stays within the evidence" intro={`${BRAND_NAME}'s public security story is about boundaries: protected access, accountable records, and no unnecessary collection.`}><div className="grid gap-4 md:grid-cols-3"><TranslatedCard prefix="security.access" title="Protected access" body="Authentication and authorization keep administrative data behind the application." /><TranslatedCard prefix="security.privacy" title="Privacy-aware evidence" body="Public pages do not expose device, school, policy, or audit records." /><TranslatedCard prefix="security.fail_closed" title="Fail-closed principles" body="Security controls are designed to avoid silently granting access when conditions fail." /></div></Page> }

export function ArchitecturePage() { const { text } = useLandingLanguage(); const components = [['administrator', 'Administrator'], ['react', 'React + Vite'], ['flask', 'Flask API'], ['database', 'PostgreSQL / Redis'], ['android', 'Android DPC']] as const; return <Page prefix="architecture" eyebrow="Architecture" title="A simple architecture with an explicit boundary" intro="The repository documents the web administrator surface and backend contracts; the Android DPC remains an external verification boundary."><div className="rounded-3xl bg-slate-950 p-8 text-white"><div className="grid gap-4 md:grid-cols-5">{components.map(([key, fallback], index) => <div key={key} className="rounded-2xl border border-white/15 bg-white/5 p-5"><span className="text-sm text-lime-300">0{index + 1}</span><p className="mt-8 font-bold">{text(`architecture.${key}`, fallback)}</p></div>)}</div><p className="mt-8 max-w-2xl text-white/70">{text('architecture.body', 'Repository-verified components and external verification requirements are intentionally shown separately.')}</p></div></Page> }

export function ResourcesPage() { const { text } = useLandingLanguage(); const links = [['/how-it-works', 'resources.how.title', 'How it works', 'resources.how', 'Follow the policy lifecycle.'], ['/architecture', 'resources.architecture.title', 'Architecture', 'resources.architecture', 'See the system boundary.'], ['/security', 'resources.security.title', 'Security', 'resources.security', 'Review the trust model.'], ['/about', 'resources.about.title', 'About the PoC', 'resources.about', 'Understand the scope.'], ['/schools', 'resources.schools.title', 'For schools', 'resources.schools', 'Explore stakeholder context.'], ['/contact', 'resources.contact.title', 'Contact', 'resources.contact', 'Ask for a walkthrough.']] as const; return <Page prefix="resources" eyebrow="Resources" title="Resources for understanding the PoC" intro={`Start with the ${BRAND_NAME} operating model, then inspect the architecture and security boundaries.`}><div className="grid gap-4 md:grid-cols-3">{links.map(([href, titleKey, title, bodyKey, body]) => <FeatureCard key={href} title={text(titleKey, title)} text={text(bodyKey, body)} href={href} />)}</div></Page> }

export function AboutPage() { return <Page prefix="about" eyebrow="About the PoC" title="An academic project with transparent scope" intro={`${BRAND_NAME} is a final-year academic Proof-of-Concept for offline-first phone-use policy enforcement on school-owned Android devices in Ugandan secondary schools.`}><div className="max-w-3xl space-y-5 leading-8 text-slate-700"><TranslatedParagraph keyName="about.body1" fallback="The project explores how policy management, device status, offline operation, and security-event evidence can fit together in a local school context." /><TranslatedParagraph keyName="about.body2" fallback="It is not presented as a finished commercial MDM/UEM platform. Android DPC validation, production rollout, and hosted-environment readiness remain separate engineering and operational gates." /></div></Page> }

export function ContactPage() { const { text } = useLandingLanguage(); return <Page prefix="contact" eyebrow="Contact" title={`Start a conversation about ${BRAND_NAME}`} intro="For a walkthrough or academic discussion, contact the project team without sending student, device, credential, or sensitive school data through this public page."><div className="rounded-2xl border border-slate-200 bg-white p-7"><p className="leading-7 text-slate-600">{text('contact.body', 'A real submission endpoint is not part of the current frontend contract. Connect an approved mail or form service before adding collection behavior.')}</p><a className="mt-6 inline-flex rounded-full border border-slate-300 px-5 py-3 font-bold text-slate-800" href="/about">{text('contact.link', 'Read the PoC scope')}</a></div></Page> }

function TranslatedParagraph({ keyName, fallback }: { keyName: string; fallback: string }) { const { text } = useLandingLanguage(); return <p>{text(keyName, fallback)}</p> }
function ScopeNote() { const { text } = useLandingLanguage(); return <aside className="rounded-2xl bg-[#e5f0dc] p-7"><Database className="size-6 text-emerald-800" /><h2 className="mt-5 text-xl font-bold">{text('common.scope_note_title', 'Scope note')}</h2><p className="mt-3 leading-7 text-slate-700">{text('common.scope_note_body', 'This public explanation uses repository evidence and marks Android DPC behavior, device certification, and production operation as separate verification requirements.')}</p></aside> }
