"""Wire protocol versions used by the Android control-plane contracts."""

POLICY_PROTOCOL_VERSION = 3
POLICY_SCHEMA_VERSION = 3
AUDIT_PROTOCOL_VERSION = 3
CONTROL_STATE_PROTOCOL_VERSION = 3
DEVICE_AUTH_PROTOCOL_VERSION = 1

__all__ = [
    "AUDIT_PROTOCOL_VERSION",
    "CONTROL_STATE_PROTOCOL_VERSION",
    "DEVICE_AUTH_PROTOCOL_VERSION",
    "POLICY_PROTOCOL_VERSION",
    "POLICY_SCHEMA_VERSION",
]
