"""Create the policies table.

Revision ID: 203748fda298
Revises: a2b94c33c0a3
Create Date: 2026-07-16 22:01:08.476843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "203748fda298"
down_revision = "a2b94c33c0a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("policy_uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "blocked_apps",
            sa.JSON(),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version >= 1",
            name="ck_policies_version_positive",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_uuid", name="uq_policies_policy_uuid"),
    )
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.create_index(
            "ix_policies_policy_uuid",
            ["policy_uuid"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.drop_index("ix_policies_policy_uuid")

    op.drop_table("policies")
    # ### end Alembic commands ###
