"""Create the device-policy assignments table.

Revision ID: 3a6f4a9eb4f2
Revises: 203748fda298
Create Date: 2026-07-16 22:17:39.149226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a6f4a9eb4f2"
down_revision = "203748fda298"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_policy_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.Column(
            "policy_version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "superseded_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "(status = 'active' AND superseded_at IS NULL) OR "
            "(status = 'superseded' AND superseded_at IS NOT NULL)",
            name="ck_device_policy_assignments_status_timestamp",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'superseded')",
            name="ck_device_policy_assignments_status",
        ),
        sa.CheckConstraint(
            "policy_version >= 1",
            name="ck_device_policy_assignments_version_positive",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "device_policy_assignments",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            "ix_device_policy_assignments_device_history",
            ["device_id", "assigned_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_device_policy_assignments_policy_id",
            ["policy_id"],
            unique=False,
        )
        batch_op.create_index(
            "uq_device_policy_assignments_active_device",
            ["device_id"],
            unique=True,
            postgresql_where=sa.text("status = 'active'"),
            sqlite_where=sa.text("status = 'active'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "device_policy_assignments",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            "uq_device_policy_assignments_active_device",
            postgresql_where=sa.text("status = 'active'"),
            sqlite_where=sa.text("status = 'active'"),
        )
        batch_op.drop_index("ix_device_policy_assignments_policy_id")
        batch_op.drop_index("ix_device_policy_assignments_device_history")

    op.drop_table("device_policy_assignments")
    # ### end Alembic commands ###
